### ISSUE TITLE
Rendering glitch if line has two dollar signs

### ISSUE THREAD

**Issue by nhed** [volca/markdown-preview#101] opened 2019-04-18 23:29 UTC
Simplest input form
```
$ $
```

Renders
```
<span class="katex"><span class="katex-mathml"><math><semantics><mrow></mrow><annotation encoding="application/x-tex"> </annotation></semantics></math></span><span class="katex-html" aria-hidden="true"></span></span>
```

I have a slightly more interesting example in https://gist.github.com/nhed/ba813bfc3f2e69cd2bc41ea3ec4a9cd6

Which renders like this:
![image](https://user-images.githubusercontent.com/513759/56397091-3b930380-6210-11e9-9b67-abd875955519.png)

**Comment by klieret** [comment] 2019-12-03 13:33
I see exactly the same issue.

That's quite a big problem if you have lot's of shell code snippets in your markdown...

**Comment by zgce** [comment] 2020-11-10 11:47
if you have lot's of shell code snippets in your markdown

Deselect KaTeX support in Options.

**Comment by volca** [comment] 2022-05-06 01:47
Can't reproduce any more. Close it. Reopen the issue if you need

**Closed by volca** 2022-05-06 01:47 UTC
