### ISSUE TITLE
Support "file:" URLs

### ISSUE THREAD

**Issue by lsloan** [volca/markdown-preview#72] opened 2017-09-29 16:16 UTC
Although the screenshot image in the Chrome web store shows this extension supports "file:" URLs, it's not true.  It doesn't work.

**Comment by cxw42** [comment] 2017-10-31 12:24
Did you check "Allow access to file URLs" in `chrome://extensions`?  It works fine for me.

![](https://camo.githubusercontent.com/0947f90b1db6b8f61ccb5d5fde7f7a91c7d97a8c/687474703a2f2f692e696d6775722e636f6d2f717468334b2e706e67)

**Comment by volca** [comment] 2017-11-13 02:21
Hi @lsloan 

Could you please check it? 

I'll close the issue.  You can reopen it if the issue is unresolved.

**Closed by volca** 2017-11-13 02:21 UTC
